language: php
php:
  - 5.4
before_script: pyrus install -p pyrus.net/Pyrus_Developer-alpha && make
script: pyrus run-phpt -r tests || (find . -name *.out | xargs -t cat && exit 1)
branches:
  only:
    - develop
