/**
 * This file is part of the UNL WDN templates.
 * @see http://wdn.unl.edu/
 * $Id$
 */
var _gaq=_gaq||[],WDN=function(){var c={};return{loadedJS:{},template_path:"",loadJS:function(a,b,d,e){if(a.match(/^\/?wdn\/templates_3\.0/)){if(a.charAt(0)=="/")a=a.substring(1);a=WDN.template_path+a}if(arguments.length>2&&d===false||!WDN.loadedJS[a])if(a in c)b&&c[a].push(b);else{c[a]=[];var f=document.createElement("script");f.setAttribute("src",a);f.setAttribute("type","text/javascript");document.getElementsByTagName("head").item(0).appendChild(f);b&&c[a].push(b);var i=function(){WDN.loadedJS[a]=
1;for(var j=0;j<c[a].length;j++)c[a][j]();delete c[a]};f.onreadystatechange=function(){if(f.readyState=="loaded"||f.readyState=="complete")i()};f.onload=i}else arguments.length>3&&e===false||!b||b()},loadCSS:function(a){if(a.match(/^wdn\/templates_3\.0/))a=WDN.template_path+a;var b=document.createElement("link");b.href=a;b.rel="stylesheet";b.type="text/css";document.getElementsByTagName("head")[0].appendChild(b)},initializeTemplate:function(){WDN.loadCSS("wdn/templates_3.0/css/script.css");WDN.loadJS("wdn/templates_3.0/scripts/xmlhttp.js");
WDN.loadJS("wdn/templates_3.0/scripts/global_functions.js")},jQueryUsage:function(){if(!WDN.jQuery)WDN.jQuery=jQuery.noConflict(true);WDN.jQuery(document).ready(function(){WDN.initializePlugin("analytics");if(!WDN.jQuery("body").hasClass("mobile")){WDN.initializePlugin("navigation");WDN.initializePlugin("search");WDN.initializePlugin("feedback");WDN.initializePlugin("socialmediashare");WDN.contentAdjustments();WDN.initializePlugin("tooltip");WDN.initializePlugin("toolbar");WDN.initializePlugin("tabs");
WDN.initializePlugin("unlalert");WDN.browserAdjustments();WDN.screenAdjustments()}})},log:function(a){"console"in window&&"log"in console&&console.log(a)},browserAdjustments:function(){if(WDN.jQuery.browser.msie&&WDN.jQuery.browser.version=="6.0"&&!navigator.userAgent.match(/MSIE 8.0/)){WDN.jQuery("body").prepend('<div id="wdn_upgrade_notice"></div>');fetchURLInto("http://www.unl.edu/wdn/templates_3.0/includes/browserupgrade.html","wdn_upgrade_notice");WDN.jQuery("head link[rel=stylesheet]").each(function(){this.disabled=
true});WDN.jQuery("body").removeAttr("class");WDN.jQuery("body").addClass("document");WDN.loadCSS("wdn/templates_3.0/css/content/columns.css")}if(navigator.userAgent.match(/applewebkit/i)&&!navigator.userAgent.match(/Version\/[34]/)||navigator.userAgent.match(/firefox/i)&&(navigator.userAgent.match(/firefox\/[12]/i)||navigator.userAgent.match(/firefox\/3.[01234]/i))||navigator.userAgent.match(/msie/i)){WDN.jQuery("table.zentable tbody tr:nth-child(odd)").addClass("rowOdd");WDN.jQuery("table.zentable tbody tr:nth-child(even)").addClass("rowEven")}},
screenAdjustments:function(){if(screen.width<=1024){WDN.jQuery("body").css({background:"#e0e0e0"});WDN.jQuery("#wdn_wrapper").css({"border-left-width":"0","border-right-width":"0"});if(WDN.jQuery.browser.msie)WDN.jQuery("#wdn_wrapper").css({margin:"0 0 0 5px"});else if(WDN.jQuery.browser.mozilla)WDN.jQuery("#wdn_wrapper").css({"-moz-border-radius":"0"});else WDN.jQuery.browser.webkit&&WDN.jQuery("#wdn_wrapper").css({"-webkit-border-radius":"0"})}},contentAdjustments:function(){WDN.jQuery("#maincontent p.caption, #footer p.caption").each(function(){WDN.jQuery(this).height()>
20&&WDN.jQuery(this).css({border:"1px solid #ededed",marginleft:"0"});WDN.jQuery(this).width(WDN.jQuery(this).prev("img").width())});WDN.jQuery("#maincontent a img, #footer a img").each(function(){WDN.jQuery(this).parent("a").addClass("imagelink")})},initializePlugin:function(a,b){b||(b=function(){"initialize"in WDN[a]&&WDN[a].initialize()});WDN.loadJS("wdn/templates_3.0/scripts/"+a+".js",b)},setCookie:function(a,b,d){var e="";if(d){e=new Date;e.setTime(e.getTime()+d*1E3);e=";expires="+e.toGMTString()}document.cookie=
a+"="+b+e+";path=/;domain=.unl.edu"},getCookie:function(a){a=a+"=";for(var b=document.cookie.split(";"),d=0;d<b.length;d++){for(var e=b[d];e.charAt(0)===" ";)e=e.substring(1,e.length);if(e.indexOf(a)===0)return e.substring(a.length,e.length)}return null},toAbs:function(a,b){var d=a.split("/");if(/http:|https:|ftp:/.test(d[0]))return a;b=b.split("/");b.length>3&&b.pop();if(d[0]===""){b=b[0]+"//"+b[2];b=b.split("/");delete d[0]}for(a=0;a<d.length;a++){if(d[a]===".."){if(typeof d[a-1]!=="undefined")delete d[a-
1];else b.length>3&&b.pop();delete d[a]}d[a]==="."&&delete d[a]}var e=[];for(a=0;a<d.length;a++)if(typeof d[a]!=="undefined")e[e.length]=d[a];return b.join("/")+"/"+e.join("/")},stringToXML:function(a){var b;try{if(window.ActiveXObject){b=new ActiveXObject("Microsoft.XMLDOM");b.async="false";b.loadXML(a)}else b=(new DOMParser).parseFromString(a,"text/xml")}catch(d){}return b},request:function(a,b,d,e,f){var i=WDN.jQuery;if(!f||!/^(get|post)$/i.test(f))f="get";f=f.toLowerCase();try{i[f](a,b,d,e);if(window.opera&&
Object.toString(window.opera.version).indexOf("[native code]")>0)throw"Opera";}catch(j){if(b&&i.isPlainObject(b)){var g="";for(var m in b)g=g+"&"+m+"="+b[m]}if(g&&f=="get"){/\?/.test(a)||(a+="?");a+=g.substr(1,g.length);g=null}if(window.XDomainRequest){b=new XDomainRequest;b.open(f,a);b.onload=function(){var h=this.responseText,k=(e||"").toLowerCase();if(typeof h=="string"&&k=="xml")h=WDN.stringToXML(h);d(h,"success",this)};b.send(g)}else try{var l=new WDN.proxy_xmlhttp;l.open(f.toUpperCase(),a,true);
f=="post"&&l.setRequestHeader("Content-Type","application/x-www-form-urlencoded");l.onreadystatechange=function(){var h="error",k="error";if(this.readyState==4&&this.status=="200"){h="success";k=this.responseText}d(k,h,this)};l.send(g)}catch(n){}}},get:function(a,b,d,e){WDN.request(a,b,d,e,"GET")},post:function(a,b,d,e){WDN.request(a,b,d,e,"POST")}}}();WDN.template_path="/";WDN.loadedJS["/wdn/templates_3.0/scripts/wdn.js"]=1;
WDN.analytics=function(){return{thisURL:String(window.location),rated:false,initialize:function(){_gaq.push(["_setAccount","UA-3203435-1"],["_setDomainName",".unl.edu"],["_setAllowLinker",true],["_setAllowHash",false]);WDN.loadJS("wdn/templates_3.0/scripts/idm.js",function(){WDN.idm.initialize(function(){WDN.analytics.loadGA()})});filetypes=/\.(zip|exe|pdf|doc*|xls*|ppt*|mp3|m4v)$/i;WDN.jQuery("#navigation a[href], #maincontent a[href]").each(function(){var c=WDN.jQuery(this).attr("href");if(c.match(/^https?\:/i)&&
!c.match(document.domain))WDN.jQuery(this).click(function(){WDN.analytics.callTrackEvent("Outgoing Link",c,WDN.analytics.thisURL)});else if(c.match(/^mailto\:/i))WDN.jQuery(this).click(function(){var a=c.replace(/^mailto\:/i,"");WDN.analytics.callTrackEvent("Email",a,WDN.analytics.thisURL)});else c.match(filetypes)&&WDN.jQuery(this).click(function(){/[.]/.exec(c)&&/[^.]+$/.exec(c);WDN.analytics.callTrackEvent("File Download",c,WDN.analytics.thisURL);WDN.analytics.callTrackPageview(c)})});WDN.jQuery("ul.socialmedia a").click(function(){var c=
WDN.jQuery(this).attr("id");WDN.analytics.callTrackEvent("Page Sharing",c,WDN.analytics.thisURL)});WDN.jQuery("#wdn_tool_links a").click(function(){var c=WDN.jQuery(this).text();WDN.analytics.callTrackEvent("WDN Tool Links",c,WDN.analytics.thisURL)});WDN.jQuery("div.rating div.star a").click(function(){if(!WDN.analytics.rated){WDN.analytics.rated=true;var c=WDN.jQuery(this).text();WDN.analytics.callTrackEvent("Page Rating","Rated a "+c,WDN.analytics.thisURL,c)}})},loadGA:function(){_gaq.push(["_trackPageview"]);
(function(){var c=document.createElement("script");c.type="text/javascript";c.async=true;c.src=("https:"==document.location.protocol?"https://ssl":"http://www")+".google-analytics.com/ga.js";var a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(c,a)})()},trackNavigationPreferredState:function(c){try{WDN.analytics.callTrackEvent("Navigation Preference",c,WDN.analytics.thisURL)}catch(a){}},callTrackPageview:function(c){if(c){_gaq.push(["_trackPageview",c]);try{pageTracker._trackPageview(c)}catch(a){}}else _gaq.push(["_trackPageview"])},
callTrackEvent:function(c,a,b,d){if(d===undefined)d=0;_gaq.push(["_trackEvent",c,a,b,d]);try{pageTracker._trackEvent(c,a,b,d)}catch(e){}}}}();WDN.loadedJS["/wdn/templates_3.0/scripts/analytics.js"]=1;WDN.loadedJS["/wdn/templates_3.0/scripts/xmlhttp.js"]=1;WDN.loadedJS["/wdn/templates_3.0/scripts/global_functions.js"]=1;WDN.initializeTemplate();
