/**
 * This file is part of the UNL WDN templates.
 * @see http://wdn.unl.edu/
 * $Id$
 */
var _gaq=_gaq||[],WDN=function(){var f={};return{loadedJS:{},template_path:"",loadJS:function(a,b,c,d){if(a.match(/^\/?wdn\/templates_3\.0/)){if(a.charAt(0)=="/")a=a.substring(1);a=WDN.template_path+a}if(arguments.length>2&&c===false||!WDN.loadedJS[a])if(a in f)b&&f[a].push(b);else{f[a]=[];var e=document.createElement("script");e.setAttribute("src",a);e.setAttribute("type","text/javascript");document.getElementsByTagName("head").item(0).appendChild(e);b&&f[a].push(b);var i=function(){WDN.loadedJS[a]=
1;if(f[a]){for(var j=0;j<f[a].length;j++)f[a][j]();delete f[a]}};e.onreadystatechange=function(){if(e.readyState=="loaded"||e.readyState=="complete")i()};e.onload=i}else arguments.length>3&&d===false||!b||b()},loadCSS:function(a){if(a.match(/^wdn\/templates_3\.0/))a=WDN.template_path+a;var b=document.createElement("link");b.href=a;b.rel="stylesheet";b.type="text/css";document.getElementsByTagName("head")[0].appendChild(b)},initializeTemplate:function(){WDN.loadCSS("wdn/templates_3.0/css/script.css");
WDN.loadJS("wdn/templates_3.0/scripts/xmlhttp.js");WDN.loadJS("wdn/templates_3.0/scripts/global_functions.js");WDN.loadJQuery(WDN.jQueryUsage)},loadJQuery:function(a){WDN.loadJS("wdn/templates_3.0/scripts/jquery.js",function(){if(!WDN.jQuery)WDN.jQuery=jQuery.noConflict(true);WDN.jQuery(document).ready(function(){a()})})},jQueryUsage:function(){WDN.initializePlugin("analytics");if(!WDN.jQuery("body").hasClass("mobile")){WDN.initializePlugin("mobile_detect");WDN.initializePlugin("navigation");WDN.initializePlugin("search");
WDN.initializePlugin("feedback");WDN.initializePlugin("socialmediashare");WDN.contentAdjustments();WDN.initializePlugin("tooltip");WDN.initializePlugin("toolbar");WDN.initializePlugin("tabs");WDN.initializePlugin("unlalert");WDN.browserAdjustments();WDN.screenAdjustments()}},log:function(a){"console"in window&&"log"in console&&console.log(a)},browserAdjustments:function(){if(WDN.jQuery.browser.msie&&WDN.jQuery.browser.version=="6.0"&&!navigator.userAgent.match(/MSIE 8.0/)){WDN.jQuery("body").prepend('<div id="wdn_upgrade_notice"></div>');
fetchURLInto("http://www.unl.edu/wdn/templates_3.0/includes/browserupgrade.html","wdn_upgrade_notice");WDN.jQuery("head link[rel=stylesheet]").each(function(){this.disabled=true});WDN.jQuery("body").removeAttr("class");WDN.jQuery("body").addClass("document");WDN.loadCSS("wdn/templates_3.0/css/content/columns.css")}if(navigator.userAgent.match(/applewebkit/i)&&!navigator.userAgent.match(/Version\/[34]/)||navigator.userAgent.match(/firefox/i)&&(navigator.userAgent.match(/firefox\/[12]/i)||navigator.userAgent.match(/firefox\/3.[01234]/i))||
navigator.userAgent.match(/msie/i)){WDN.jQuery(".zentable tbody tr:nth-child(odd)").addClass("rowOdd");WDN.jQuery(".zentable tbody tr:nth-child(even)").addClass("rowEven")}},screenAdjustments:function(){if(screen.width<=1024){WDN.jQuery("body").css({background:"#e0e0e0"});WDN.jQuery.browser.msie&&WDN.jQuery("#wdn_wrapper").css({margin:"0 0 0 5px"})}},contentAdjustments:function(){WDN.jQuery("#footer_floater").css("zoom",1);WDN.jQuery("#maincontent p.caption, #footer p.caption").each(function(){WDN.jQuery(this).height()>
20&&WDN.jQuery(this).css({border:"1px solid #DDD",marginleft:"0"});var a=WDN.jQuery(this).prev("img").width();a&&WDN.jQuery(this).width(a)});WDN.jQuery("#maincontent a img, #footer a img").each(function(){WDN.jQuery(this).parent("a").addClass("imagelink")})},initializePlugin:function(a,b){b||(b=function(){"initialize"in WDN[a]&&WDN[a].initialize()});WDN.loadJS("wdn/templates_3.0/scripts/"+a+".js",b)},setCookie:function(a,b,c){var d="";if(c){d=new Date;d.setTime(d.getTime()+c*1E3);d=";expires="+d.toGMTString()}document.cookie=
a+"="+b+d+";path=/;domain=.unl.edu"},getCookie:function(a){a=a+"=";for(var b=document.cookie.split(";"),c=0;c<b.length;c++){for(var d=b[c];d.charAt(0)===" ";)d=d.substring(1,d.length);if(d.indexOf(a)===0)return d.substring(a.length,d.length)}return null},toAbs:function(a,b){if(typeof a!="undefined"){var c=a.split("/");if(/http:|https:|ftp:/.test(c[0]))return a;b=b.split("/");b.length>3&&b.pop();if(c[0]===""){b=b[0]+"//"+b[2];b=b.split("/");delete c[0]}for(a=0;a<c.length;a++){if(c[a]===".."){if(typeof c[a-
1]!=="undefined")delete c[a-1];else b.length>3&&b.pop();delete c[a]}c[a]==="."&&delete c[a]}var d=[];for(a=0;a<c.length;a++)if(typeof c[a]!=="undefined")d[d.length]=c[a];return b.join("/")+"/"+d.join("/")}},stringToXML:function(a){var b;try{if(window.ActiveXObject){b=new ActiveXObject("Microsoft.XMLDOM");b.async="false";b.loadXML(a)}else b=(new DOMParser).parseFromString(a,"text/xml")}catch(c){}return b},request:function(a,b,c,d,e){var i=WDN.jQuery;if(!e||!/^(get|post)$/i.test(e))e="get";e=e.toLowerCase();
try{i[e](a,b,c,d);if(window.opera&&Object.toString(window.opera.version).indexOf("[native code]")>0)throw"Opera";}catch(j){if(b&&i.isPlainObject(b)){var g="";for(var m in b)g=g+"&"+m+"="+b[m]}if(g&&e=="get"){/\?/.test(a)||(a+="?");a+=g.substr(1,g.length);g=null}if(window.XDomainRequest&&e!="post"){b=new XDomainRequest;b.open(e,a);b.onload=function(){var h=this.responseText,k=(d||"").toLowerCase();if(typeof h=="string"&&k=="xml")h=WDN.stringToXML(h);c(h,"success",this)};b.send(g)}else try{var l=new WDN.proxy_xmlhttp;
l.open(e.toUpperCase(),a,true);e=="post"&&l.setRequestHeader("Content-Type","application/x-www-form-urlencoded");l.onreadystatechange=function(){var h="error",k="error";if(this.readyState==4&&this.status=="200"){h="success";k=this.responseText}c(k,h,this)};l.send(g)}catch(n){}}},get:function(a,b,c,d){WDN.request(a,b,c,d,"GET")},post:function(a,b,c,d){WDN.request(a,b,c,d,"POST")}}}();WDN.template_path="/";WDN.loadedJS["/wdn/templates_3.0/scripts/wdn.js"]=1;_gaq=_gaq||[];
analytics=function(){return{initialize:function(){_gaq.push(["_setAccount","UA-3203435-1"],["_setDomainName",".unl.edu"],["_setAllowLinker",true],["_setAllowHash",false]);_gaq.push(["m._setAccount","UA-3203435-4"],["m._setDomainName",".unl.edu"],["m._setAllowLinker",true],["m._setAllowHash",false]);analytics.loadGA()},loadGA:function(){_gaq.push(["_trackPageview"],["m._trackPageview"]);(function(){var f=document.createElement("script");f.type="text/javascript";f.async=true;f.src=("https:"==document.location.protocol?
"https://ssl":"http://www")+".google-analytics.com/ga.js";var a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(f,a)})()}}}();analytics.initialize();WDN.loadedJS["/wdn/templates_3.0/scripts/mobile_analytics.js"]=1;
mobile_support=function(){return{initialize:function(){window.addEventListener("orientationchange",mobile_support.setOrientation,false);mobile_support.setOrientation()},setOrientation:function(){var f=Math.abs(window.orientation)===90?"landscape":"portrait";document.getElementsByTagName("html")[0].setAttribute("class",f)}}}();mobile_support.initialize();WDN.loadedJS["/wdn/templates_3.0/scripts/mobile_support.js"]=1;
